development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:229d001fe1db9862282eff7688eb56c4@pike.redistogo.com:11037/

  channel_prefix: message_me_production
